export const CREATE_PLAYER = "CREATE_PLAYER";
export const RETRIEVE_PLAYER = "RETRIEVE_PLAYER";
export const UPDATE_PLAYER = "UPDATE_PLAYER";
export const DELETE_PLAYER = "DELETE_PLAYER";
export const DELETE_ALL_PLAYER  = "DELETE_ALL_PLAYER";